=== Description de la proposition


Motivation de base:
Le technologie a toujours été au service de l'humanité, facilité la vie quotidienne et rapproché les gens, elle n'est pas là pour faire disparaître les habitudes et les outils de divertissement sociaux, notamment les jeux de plateau et de société, mais pour leur donner une autre dimension. 
Notre projet PACT est à l'origine d'un besoin qui s'est profondément senti dans des circonstances sanitaires particulières mais qui s'avèrent indissociables de notre avenir. Le confinement, qu'il soit imposé ou choisi, a séparé les gens et rendu impossible une partie de jeu de cartes en famille avec toute la chaleur humaine. Si la crise actuelle amplifie le problème de la distance, elle n’en est pas la seule origine et le besoin de connecter des gens éloignés ne disparaîtra pas avec elle. C'est là où retentit l'idée de créer un moyen de relier des joueurs en présentiel avec d'autres à distance, avec le minimum de moyens possibles (cartes disponibles à la maison, smartphone et croupier intelligent), sans pour autant supprimer l'expérience de jeu physique, le contact avec les cartes et les conversations entre les joueurs tout en ajoutant des fonctionnalités supplémentaires tel qu’un arbitre intelligent qui vérifie l'application des règles du jeu, un historique des parties, des analyses etc. (cf. La VAR).
Problèmes constatés avant élaboration du projet, solutions proposées: 
La première contrainte qui s'impose est clairement le fait que tous les joueurs qui peuvent être à distance ou en partie autour de la même table puissent voir les cartes jouées par le groupe en présentiel. Chacun dispose de son propre jeu de cartes. Il faut donc, pour intégrer tous les joueurs dans la partie, éviter les doublons en éliminant les cartes présentes en main des joueurs de la pioche sans que les autres s'en rendent compte. Le "croupier intelligent" se charge donc de distribuer les cartes des joueurs présents physiquement en plus de celles du joueur à distance qu’il sort du paquet et conserve de côté.
De surcroît, la faisabilité du projet et la propension des utilisateurs à l'accueillir positivement impose de garder l'expérience de jeu la plus naturelle possible même si un joueur est à distance. Le croupier joue alors les cartes que le joueur absent sélectionne, et donc ce dernier est le seul à suivre le jeu en entier sur son écran. Les autres joueurs peuvent jouer avec de vraies cartes physiques. De plus, tous les joueurs peuvent accéder à des statistiques et des informations utiles sur la partie en cours ou les parties antérieures.

